# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rundown < Formula
  desc "Rundown runs Markdown files, making them powerful and pretty console applications"
  homepage "https://github.com/elseano/rundown"
  version "0.4.0-beta.12"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.12/rundown_0.4.0-beta.12_Darwin_x86_64.tar.gz"
    sha256 "7eada347d979578a29a525441d11555e505eef042ff90d11763777b8829c0f04"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.12/rundown_0.4.0-beta.12_Darwin_arm64.tar.gz"
    sha256 "dbbec466c6f65faffb113189cb812759b50b1cddcd45cc6f1f302bff45297c6e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.12/rundown_0.4.0-beta.12_Linux_x86_64.tar.gz"
    sha256 "72da4ee5ab96c2437ff07863aa26a4a3435fb10adfbb395d8196cf8fa1420cbc"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.12/rundown_0.4.0-beta.12_Linux_arm64.tar.gz"
    sha256 "c82051a675316cd947b160a66448fd873cd4537c10ce8b60cc9a9154f9e23151"
  end

  def install
    bin.install "rundown"

    output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "bash")
    (bash_completion/"rundown").write output

    output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "zsh")
    (zsh_completion/"rundown").write output

    output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "fish")
    (fish_completion/"rundown").write output
  end

  test do
    assert_match "rundown version #{version}", shell_output("#{bin}/rundown --version")
  end
end
