# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rundown < Formula
  desc "Rundown runs Markdown files, making them powerful and pretty console applications"
  homepage "https://github.com/elseano/rundown"
  version "0.4.0-beta.5"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.5/rundown_0.4.0-beta.5_Darwin_x86_64.tar.gz"
    sha256 "e11eb4bb35b742081cdb0b55b398db2adab2e7897a6e902677f93d97c2eaf3a0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.5/rundown_0.4.0-beta.5_Darwin_arm64.tar.gz"
    sha256 "faef756837ad0562004ca1a93dc0694929bc406ebb32da411585ed5b5079386a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.5/rundown_0.4.0-beta.5_Linux_x86_64.tar.gz"
    sha256 "e83086567cb0691bd37002cacaa612a553559ff0a7c431ca512d64c8639d18cf"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/elseano/rundown/releases/download/v0.4.0-beta.5/rundown_0.4.0-beta.5_Linux_arm64.tar.gz"
    sha256 "eab8288bc8c46361ab7b34da54090bb819d26e91941609062a198276b2021753"
  end

  def install
    bin.install "rundown"

    output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "bash")
    (bash_completion/"rundown").write output

    output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "zsh")
    (zsh_completion/"rundown").write output

    output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "fish")
    (fish_completion/"rundown").write output
  end

  test do
    assert_match "rundown version #{version}", shell_output("#{bin}/rundown --version")
  end
end
